### ISSUE TITLE
"Coordinated Universal Time" isn't valid. Consider using UTC-offset

### ISSUE THREAD

**Issue by frankhaugen** [logiqsystem/cronquery#6]
Hi

I'm implementing your great library in some services/applications and I need to follow UTC, but writing the actual name of the UTC timezone, (Coordinated Universal Time), I get an exception.

This is a serious flaw in the logic of the library, (you have created a library so it must be as idiot-proof as possible)

- Timezone should be represented by an off-set:
> 0 - Means UTC
> 4 - means UTC-04
> 5:45 - means UTC+05:24 (Nepalease time)

- Lack of any settings, the default should be UTC
- If, not going to an off-set system, please rely on standardiced names for the time-zones as according to wikipedia, the exaples you have in your code arn't existing timezones: [Timezones](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations)

There should at least be a list of allowed timezone names in the documentation, until changes are made.

Thank you for your time and your very useful nuget

**Comment by frankhaugen** [comment]
I created PR containing the "fix": #9

**Comment by marxjmoura** [comment]
Hi @frankhaugen, sorry for taking so long to answer you. I will try to answer all your points.

The library uses the native `TimeZoneInfo.FindSystemTimeZoneById()` method. You can get the available time zones by calling the `TimeZoneInfo.GetSystemTimeZones()` method (I will clarify this in the documentation, thanks).

The exception thrown is the [`System.TimeZoneNotFoundException`](https://docs.microsoft.com/en-us/dotnet/api/system.timezonenotfoundexception?view=netframework-4.7.2). This exception does not exactly mean that the time zone is invalid, it only tells us that the provided time zone was not found on the local computer.

Regarding your suggestion:

> Lack of any settings, the default should be UTC

This is the [current behavior](https://github.com/logiqsystem/cronquery/blob/master/src/api/Mvc/Jobs/JobRunner.cs#L98) of the library. :)

And finally, thanks very much for your contribution. I will review your PR as soon as I can.

**Comment by frankhaugen** [comment]
Yes, I found the part of the code that specified UTC as default, but without the documentation, (as far as I found), communicating this. I was required to actually look at the code. This is probably a case of overly nit-pickery from my part

**Comment by marxjmoura** [comment]
PR https://github.com/logiqsystem/cronquery/pull/9 merged. Wait for a new version very soon.
