### ISSUE TITLE
No support for .net core 3.0.100-preview3-010431

### ISSUE THREAD

**Issue by frankhaugen** [logiqsystem/cronquery#7]
Being on the cutting edge is important, so as a near-future-feature I reqest that yopu look into making it compatible with dotnet core 3.0.100-preview3-010431

**Comment by frankhaugen** [comment]
Look into Pull Request: #8 

Just did it for you, (I'm really keen on getting this into a project I'm working on at work). :-)

**Comment by marxjmoura** [comment]
Nice! Let's get the work done! :sunglasses:

**Comment by marxjmoura** [comment]
PR https://github.com/logiqsystem/cronquery/pull/8 is in the master branch. It will be available in the next release. :)
